### ISSUE TITLE
TypeError: listdir() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by Jolty95** [OctoNezd/TWLBoxArts#1]
First of all, thanks for uploading this (and sorry my English mistakes)

I've tried to use on Windows 10 x64 with 2 problems. First, I think is a good idea to put on readme.md to install pillow on windows `python -m pip install pillow` because for example, people like me we that are not used to use python everyday can enconter with a  ImportError: No module named PIL exception and I think it can be usefull for other people to include that line in readme :) 
Second, after installing pillow, in line 5 I get `TypeError: listdir() takes exactly 1 argument (0 given)`. 
Thanks for all :)

**Comment by OctoNezd** [comment]
Looks like you are running python2, are you?

**Comment by OctoNezd** [comment]
Because on mine python version(3.5) listdir accepts 0 or more args

**Comment by OctoNezd** [comment]
In python3.2 this function changed and `path` is optional

**Comment by Jolty95** [comment]
Yes, I'm using python 2. Didn't know that.
